import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';

import { ApiError } from '@/services/api/client';
import { createReview } from '@/services/api/reviews';

export default function ReviewScreen(){const router=useRouter();const {id}=useLocalSearchParams<{id:string}>();const [rating,setRating]=useState(0);const [comment,setComment]=useState('');const [saving,setSaving]=useState(false);const submit=async()=>{if(!rating){Alert.alert('Rating required','Choose a rating before submitting.');return;}setSaving(true);try{await createReview(id,rating,comment.trim()||undefined);Alert.alert('Thank you','Your review has been submitted.');router.replace(`/bookings/${id}` as never);}catch(caught){Alert.alert('Unable to submit review',caught instanceof ApiError?caught.message:'Please try again.');}finally{setSaving(false);}};return <SafeAreaView style={styles.safeArea}><View style={styles.content}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={25} color="#0F172A"/></Pressable><Text style={styles.title}>Rate your service</Text><Text style={styles.sub}>Your feedback helps us improve and supports professionals.</Text><View style={styles.stars}>{[1,2,3,4,5].map(value=><Pressable key={value} onPress={()=>setRating(value)} hitSlop={8}><Ionicons name={value<=rating?'star':'star-outline'} size={42} color={value<=rating?'#F59E0B':'#CBD5E1'}/></Pressable>)}</View><Text style={styles.ratingLabel}>{rating?`${rating} out of 5`:'Tap a star to rate'}</Text><TextInput value={comment} onChangeText={setComment} maxLength={1000} multiline textAlignVertical="top" placeholder="Share your experience (optional)" style={styles.input}/><Pressable disabled={saving} onPress={()=>void submit()} style={styles.button}>{saving?<ActivityIndicator color="#FFF"/>:<Text style={styles.buttonText}>Submit review</Text>}</Pressable></View></SafeAreaView>}
const styles=StyleSheet.create({safeArea:{flex:1,backgroundColor:'#F8FAFC'},content:{padding:20},title:{fontSize:25,fontWeight:'900',color:'#0F172A',marginTop:30},sub:{fontSize:14,color:'#64748B',lineHeight:21,marginTop:8},stars:{flexDirection:'row',justifyContent:'space-between',marginTop:34},ratingLabel:{fontSize:14,fontWeight:'800',color:'#334155',textAlign:'center',marginTop:14},input:{height:140,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',borderRadius:14,padding:14,fontSize:14,color:'#0F172A',marginTop:30},button:{height:54,backgroundColor:'#00A651',borderRadius:14,alignItems:'center',justifyContent:'center',marginTop:18},buttonText:{color:'#FFF',fontSize:16,fontWeight:'900'}});
