import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import type { ComponentProps } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';

import { ApiError } from '@/services/api/client';
import { AdminDashboard, getAdminDashboard } from '@/services/api/admin';

export default function AdminDashboardScreen(){const router=useRouter();const [data,setData]=useState<AdminDashboard|null>(null);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState<string|null>(null);const load=useCallback(async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);setError(null);try{setData(await getAdminDashboard());}catch(caught){setError(caught instanceof ApiError?caught.message:'Dashboard could not be loaded.');}finally{setLoading(false);setRefreshing(false);}},[]);useFocusEffect(useCallback(()=>{void load();},[load]));if(loading)return <SafeAreaView style={styles.center}><ActivityIndicator color="#00A651"/></SafeAreaView>;if(error)return <SafeAreaView style={styles.center}><Text style={styles.error}>{error}</Text><Pressable onPress={()=>void load()} style={styles.primary}><Text style={styles.primaryText}>Try again</Text></Pressable></SafeAreaView>;return <SafeAreaView style={styles.safeArea}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)}/>} contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.title}>Admin dashboard</Text><Text style={styles.subtitle}>Live business overview</Text></View><Pressable onPress={()=>router.back()}><MaterialCommunityIcons name="close" size={24} color="#0F172A"/></Pressable></View><View style={styles.kpis}><Kpi label="Revenue" value={`₹${data?.paidRevenue??0}`} icon="cash-multiple"/><Kpi label="Bookings" value={String(data?.bookings??0)} icon="calendar-check"/><Kpi label="Customers" value={String(data?.customers??0)} icon="account-group"/><Kpi label="Technicians" value={String(data?.technicians??0)} icon="account-hard-hat"/></View><View style={styles.card}><Text style={styles.cardTitle}>Operations</Text><Row label="Verified technicians" value={data?.verifiedTechnicians??0}/><Row label="Pending payments" value={data?.pendingPayments??0}/></View><View style={styles.card}><Text style={styles.cardTitle}>Bookings by status</Text>{Object.entries(data?.bookingsByStatus??{}).length?Object.entries(data?.bookingsByStatus??{}).map(([status,count])=><Row key={status} label={status.replaceAll('_',' ')} value={count}/>):<Text style={styles.subtitle}>No booking data yet.</Text>}</View></ScrollView></SafeAreaView>}
function Kpi({label,value,icon}:{label:string;value:string;icon:ComponentProps<typeof MaterialCommunityIcons>['name']}){return <View style={styles.kpi}><MaterialCommunityIcons name={icon} size={20} color="#00A651"/><Text style={styles.kpiValue}>{value}</Text><Text style={styles.kpiLabel}>{label}</Text></View>}
function Row({label,value}:{label:string;value:number}){return <View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View>}
const styles=StyleSheet.create({safeArea:{flex:1,backgroundColor:'#F8FAFC'},center:{flex:1,justifyContent:'center',alignItems:'center',gap:12},content:{padding:16,paddingBottom:36},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:20},title:{fontSize:23,fontWeight:'900',color:'#0F172A'},subtitle:{fontSize:13,color:'#64748B',marginTop:4},kpis:{flexDirection:'row',flexWrap:'wrap',gap:12},kpi:{width:'47%',backgroundColor:'#FFF',padding:15,borderRadius:15,borderWidth:1,borderColor:'#E2E8F0'},kpiValue:{fontSize:22,fontWeight:'900',color:'#0F172A',marginTop:9},kpiLabel:{fontSize:12,color:'#64748B',marginTop:2},card:{backgroundColor:'#FFF',padding:16,borderRadius:16,borderWidth:1,borderColor:'#E2E8F0',marginTop:14},cardTitle:{fontSize:15,fontWeight:'900',color:'#0F172A',marginBottom:8},row:{flexDirection:'row',justifyContent:'space-between',paddingVertical:11,borderBottomWidth:1,borderColor:'#F1F5F9'},rowLabel:{fontSize:13,color:'#475569',fontWeight:'700'},rowValue:{fontSize:14,color:'#0F172A',fontWeight:'900'},error:{color:'#991B1B',textAlign:'center'},primary:{backgroundColor:'#00A651',paddingHorizontal:18,paddingVertical:11,borderRadius:10},primaryText:{color:'#FFF',fontWeight:'800'}});
