import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { ApiError } from '@/services/api/client';
import { rescheduleBooking } from '@/services/api/bookings';

const slots = [9, 11, 13, 15, 17];
export default function RescheduleScreen() {
 const router=useRouter();const {id}=useLocalSearchParams<{id:string}>();const dates=useMemo(()=>Array.from({length:7},(_,index)=>{const date=new Date();date.setDate(date.getDate()+index+1);date.setHours(0,0,0,0);return date;}),[]);const [day,setDay]=useState(0);const [hour,setHour]=useState(11);const [reason,setReason]=useState('');const [saving,setSaving]=useState(false);
 const submit=async()=>{const scheduledAt=new Date(dates[day]);scheduledAt.setHours(hour,0,0,0);setSaving(true);try{await rescheduleBooking(id,scheduledAt.toISOString(),reason.trim()||undefined);Alert.alert('Booking rescheduled','Your new appointment time is confirmed.');router.replace(`/bookings/${id}` as never);}catch(caught){Alert.alert('Unable to reschedule',caught instanceof ApiError?caught.message:'Please try again.');}finally{setSaving(false);}};
 return <SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={()=>router.back()}><MaterialCommunityIcons name="arrow-left" size={26} color="#0F172A"/></Pressable><Text style={styles.title}>Reschedule booking</Text><View style={{width:26}}/></View><Text style={styles.heading}>Choose a new date</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.dates}>{dates.map((date,index)=><Pressable key={date.toISOString()} onPress={()=>setDay(index)} style={[styles.date,index===day&&styles.dateActive]}><Text style={[styles.weekday,index===day&&styles.textActive]}>{date.toLocaleDateString(undefined,{weekday:'short'})}</Text><Text style={[styles.day,index===day&&styles.textActive]}>{date.getDate()}</Text></Pressable>)}</ScrollView><Text style={styles.heading}>Choose a time</Text><View style={styles.slots}>{slots.map(value=><Pressable key={value} onPress={()=>setHour(value)} style={[styles.slot,value===hour&&styles.slotActive]}><Text style={[styles.slotText,value===hour&&styles.textActive]}>{new Date(2000,0,1,value).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</Text></Pressable>)}</View><Text style={styles.heading}>Reason (optional)</Text><TextInput value={reason} onChangeText={setReason} maxLength={500} multiline textAlignVertical="top" placeholder="Tell us why you need a different slot" style={styles.reason}/><Pressable disabled={saving} onPress={()=>void submit()} style={styles.primary}>{saving?<ActivityIndicator color="#FFF"/>:<Text style={styles.primaryText}>Confirm new time</Text>}</Pressable></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safeArea:{flex:1,backgroundColor:'#F8FAFC'},content:{padding:16,paddingBottom:36},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:24},title:{fontSize:19,fontWeight:'800',color:'#0F172A'},heading:{fontSize:15,fontWeight:'800',color:'#0F172A',marginBottom:10,marginTop:10},dates:{gap:9,paddingBottom:14},date:{width:62,height:72,borderRadius:14,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',alignItems:'center',justifyContent:'center'},dateActive:{backgroundColor:'#00A651',borderColor:'#00A651'},weekday:{fontSize:12,color:'#64748B',fontWeight:'700'},day:{fontSize:20,color:'#0F172A',fontWeight:'900',marginTop:3},textActive:{color:'#FFF'},slots:{flexDirection:'row',flexWrap:'wrap',gap:10},slot:{width:'47%',paddingVertical:14,borderRadius:12,borderWidth:1,borderColor:'#E2E8F0',backgroundColor:'#FFF',alignItems:'center'},slotActive:{backgroundColor:'#00A651',borderColor:'#00A651'},slotText:{fontSize:14,fontWeight:'800',color:'#334155'},reason:{height:100,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',borderRadius:12,padding:12,fontSize:14,color:'#0F172A'},primary:{height:52,borderRadius:12,backgroundColor:'#00A651',alignItems:'center',justifyContent:'center',marginTop:20},primaryText:{color:'#FFF',fontWeight:'900',fontSize:15}});
