import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { ApiError } from '@/services/api/client';
import { getMyTechnicianProfile, updateTechnicianProfile } from '@/services/api/technicians';

export default function TechnicianProfileScreen() {
 const router=useRouter();const [bio,setBio]=useState('');const [experience,setExperience]=useState('');const [skills,setSkills]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const profile=await getMyTechnicianProfile();setBio(profile.bio??'');setExperience(String(profile.experienceYears??0));setSkills(profile.skills.join(', '));}catch(caught){Alert.alert('Profile unavailable',caught instanceof ApiError?caught.message:'Please try again.');}finally{setLoading(false);}},[]);
 useFocusEffect(useCallback(()=>{void load();},[load]));
 const save=async()=>{const years=Number(experience);const normalizedSkills=skills.split(',').map((skill)=>skill.trim()).filter(Boolean);if(!Number.isInteger(years)||years<0){Alert.alert('Invalid experience','Enter whole years of experience.');return;}if(!normalizedSkills.length){Alert.alert('Skills required','Add at least one skill.');return;}setSaving(true);try{await updateTechnicianProfile({bio:bio.trim()||undefined,experienceYears:years,skills:normalizedSkills});Alert.alert('Partner profile updated','Your skills and experience are saved.');router.back();}catch(caught){Alert.alert('Unable to update',caught instanceof ApiError?caught.message:'Please try again.');}finally{setSaving(false);}};
 if(loading)return <SafeAreaView style={styles.center}><ActivityIndicator color="#00A651"/></SafeAreaView>;
 return <SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={()=>router.back()}><MaterialCommunityIcons name="arrow-left" size={26} color="#0F172A"/></Pressable><Text style={styles.title}>Partner profile</Text><View style={{width:26}}/></View><Text style={styles.intro}>Keep these details current so the right jobs can be assigned to you.</Text><View style={styles.card}><Text style={styles.label}>ABOUT YOU</Text><TextInput value={bio} onChangeText={setBio} style={[styles.input,styles.textArea]} multiline maxLength={1000} placeholder="Describe your work experience and specialties" textAlignVertical="top"/><Text style={styles.label}>EXPERIENCE IN YEARS</Text><TextInput value={experience} onChangeText={setExperience} style={styles.input} keyboardType="number-pad" maxLength={2} placeholder="e.g. 3"/><Text style={styles.label}>SKILLS</Text><TextInput value={skills} onChangeText={setSkills} style={[styles.input,styles.textArea]} multiline placeholder="e.g. Fan repair, wiring, geyser repair" textAlignVertical="top"/><Text style={styles.hint}>Separate skills with commas.</Text></View><Pressable disabled={saving} onPress={()=>void save()} style={styles.primary}>{saving?<ActivityIndicator color="#FFF"/>:<Text style={styles.primaryText}>Save partner profile</Text>}</Pressable></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safeArea:{flex:1,backgroundColor:'#F8FAFC'},center:{flex:1,alignItems:'center',justifyContent:'center'},content:{padding:16,paddingBottom:36},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:16},title:{fontSize:19,fontWeight:'800',color:'#0F172A'},intro:{fontSize:13,color:'#64748B',lineHeight:19,marginBottom:16},card:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',borderRadius:16,padding:16},label:{fontSize:11,fontWeight:'800',color:'#64748B',marginBottom:6,marginTop:8},input:{height:46,borderWidth:1,borderColor:'#E2E8F0',borderRadius:10,paddingHorizontal:12,color:'#0F172A',fontSize:14},textArea:{height:100,paddingTop:12},hint:{fontSize:11,color:'#64748B',marginTop:7},primary:{height:52,borderRadius:12,backgroundColor:'#00A651',alignItems:'center',justifyContent:'center',marginTop:18},primaryText:{color:'#FFF',fontWeight:'900',fontSize:15}});
