import { ServiceDetail } from "@/types/service";
import { carpenterDetails, carpenterServices } from "./carpenter";
import { cleaningDetails, cleaningServices } from "./cleaning";
import { electricalServices } from "./electrical";
import { applianceDetails, applianceServices } from "./homeAppliance";
import { installationServices } from "./installation";
import { inspectionDetails } from "./inspection";
import { maidDetails, maidServices } from "./maid";
import { menSalonServices } from "./menSalon";
import { paintingServices } from "./painting";
import { pestControlServices } from "./pestControl";
import { plumbingDetails, plumbingServices } from "./plumbing";
import { womenSalonServices } from "./womenSalon";

import * as electronicsModule from "./electronics";
import * as mostBookedModule from "./mostBooked";
import { services } from "./services";
import { onDemandDetails, onDemandServices } from "./ondemand";

import { Category, categoryImages, defaultImages, serviceImages } from "./serviceImages";

const getModuleArrayData = (mod: any): any[] => {
  if (!mod) return [];
  if (Array.isArray(mod.default)) return mod.default;
  const foundArray = Object.values(mod).find((val) => Array.isArray(val));
  return Array.isArray(foundArray) ? foundArray : [];
};

const getFlatWomenSalonServices = (): any[] => {
  // ✅ FIX: womenSalonServices अब पहले से ही एक flat ServiceItem[] array है
  // (पुराना कोड block.subCategories[].services[] जैसे nested structure की उम्मीद कर रहा था,
  // जो अब मौजूद नहीं है — इसी वजह से Women's Salon का डेटा कभी serviceDetails में नहीं आता था)
  if (!Array.isArray(womenSalonServices)) return [];
  // हर item का असली category "threading"/"waxing"/"facial" जैसा sub-type होता है,
  // जो /category/women-salon राउट से मैच नहीं करता — इसलिए यहाँ सिर्फ़ राउटिंग के लिए override करते हैं
  return womenSalonServices.map((item: any) => ({ ...item, category: "women-salon" }));
};

// ✅ SAFE: हर array को fallback (|| []) दें और अंत में .filter(Boolean) से undefined/null हटाएँ
const combinedAllSubServices = [
  ...(electricalServices || []),
  ...(carpenterServices || []),
  ...(Object.values(carpenterDetails || {})),
  ...(applianceServices || []),
  ...(Object.values(applianceDetails || {})),
  ...(plumbingServices || []),
  ...(Object.values(plumbingDetails || {})),
  ...(cleaningServices || []),
  ...(Object.values(cleaningDetails || {})),
  ...(Object.values(inspectionDetails || {})),
  ...(getFlatWomenSalonServices() || []),
  ...(installationServices || []),
  ...(maidServices || []),
  ...(Object.values(maidDetails || {})),
  ...(menSalonServices || []),
  ...(paintingServices || []),
  ...(pestControlServices || []),
  ...(getModuleArrayData(electronicsModule) || []),
  ...(getModuleArrayData(mostBookedModule) || []),
  ...(onDemandServices || []),
  ...(Object.values(onDemandDetails || {})),
  ...(services || []),
].filter(Boolean); // ← यह undefined, null, false को हटाता है

const defaultTechnician = {
  name: "Ravi Kumar",
  photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
  rating: 4.9,
  experience: "8 Years",
  jobs: 2500,
};

const defaultFaqs = [
  { question: "Is labour charge free?", answer: "Yes, Labour is FREE for Members." }
];

const baseParentCategories: Record<string, ServiceDetail> = {
  electrician: {
    id: "electrician",
    title: "Electrician Service",
    category: "electrical",
    visitCharge: 49,
    labourFree: true,
    membershipRequired: true,
    materialExtra: true,
    images: categoryImages.Electrical,
  }
};

const getImages = (item: any, targetCategory: Category): string[] => {
  if (serviceImages[item.id]) return serviceImages[item.id];
  const routeId = item.route?.replace("/service/", "");
  if (routeId && serviceImages[routeId]) return serviceImages[routeId];
  if (targetCategory === "SaloonWomen") return ["https://images.unsplash.com/photo-1487412720507-e7ab37603c6f"];
  return (categoryImages[targetCategory as keyof typeof categoryImages] || defaultImages);
};

const autoGeneratedDetails: Record<string, ServiceDetail> = combinedAllSubServices.reduce((acc, item) => {
  if (!item || !item.id) return acc;

  const lowerId = item.id.toLowerCase();
  const lowerTitle = (item.title || "").toLowerCase();
  let inferredCategory: Category = "General";
  
  if (lowerId.startsWith("women_") || lowerTitle.includes("women") || lowerTitle.includes("threading") || lowerTitle.includes("facial") || lowerTitle.includes("waxing")) {
    inferredCategory = "SaloonWomen";
  } else if (lowerId.startsWith("men_") || lowerTitle.includes("men salon")) {
    inferredCategory = "SaloonMen";
  } else if (lowerId.startsWith("pest_")) {
    inferredCategory = "PestControl";
  } else if (lowerId.startsWith("paint_")) {
    inferredCategory = "Painting";
  } else if (lowerId.startsWith("clean_") || lowerId.startsWith("maid_")) {
    inferredCategory = "Cleaning";
  } else if (lowerId.startsWith("install_")) {
    inferredCategory = "Installation";
  } else if (lowerId.includes("plumb") || lowerTitle.includes("plumber")) {
    inferredCategory = "Plumbing";
  } else if (lowerId.includes("carpenter") || lowerTitle.includes("carpenter")) {
    inferredCategory = "Carpenter";
  } else if (lowerId.includes("appliance") || lowerTitle.includes("ac repair")) {
    inferredCategory = "Appliance";
  } else if (lowerId.includes("electric") || lowerTitle.includes("electrician")) {
    inferredCategory = "Electrical";
  }

  const targetCategory = item.category || inferredCategory;
  const isSalonType = targetCategory === "SaloonWomen" || targetCategory === "SaloonMen";

  acc[item.id] = {
    id: item.id,
    title: item.title || "Expert Service",
    hindiTitle: item.hindiTitle || "",
    category: targetCategory as any,
    visitCharge: isSalonType ? 0 : 49,
    labourFree: true,
    membershipRequired: !isSalonType,
    materialExtra: !isSalonType,
    description: item.description ?? `Professional ${item.title || "expert"} service.`,
    includes: Array.isArray(item.includes) ? item.includes : ["Premium Service Execution"],
    technician: item.technician || defaultTechnician,
    faqs: item.faqs || defaultFaqs,
    images: Array.isArray(item.images) && item.images.length > 0 ? item.images : getImages(item, targetCategory),
    variants: Array.isArray(item.variants) ? item.variants : [],
    benefits: Array.isArray(item.benefits) ? item.benefits : [],
    brandsUsed: Array.isArray(item.brandsUsed) ? item.brandsUsed : [],
  };

  return acc;
}, {} as Record<string, ServiceDetail>);

export const serviceDetails: Record<string, ServiceDetail> = {
  ...baseParentCategories,
  ...autoGeneratedDetails,
};

export const getServiceById = (id: string): ServiceDetail | undefined => {
  return serviceDetails[id];
};

export default serviceDetails;